### ISSUE TITLE
Crash when using VS 15.3 preview

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/ProjFileTools#16]
### Installed product versions
- Visual Studio: VS 15.3 26510.0-Preview
- This extension: Project File Tools 1.0.2

### Description
Extension crashes with FileNotFoundException for NuGet.Frameworks.dll

### Steps to recreate
- Open SDK-style .csproj
- Type in an item group `<PackageReference Include="`

### Current behavior
Dialog box pops up saying there was an error.  Activity log includes the below error.  Note that this doesn't seem to always occur, it seems to generate the error the first time it tries to show intellisense, but subsequently it either successfully shows the intellisense or silently doesn't show it without popping up an error dialog.

> <description>System.AggregateException: One or more errors occurred. ---&gt; System.AggregateException: One or more errors occurred. ---&gt; System.IO.FileNotFoundException: Could not load file or assembly &apos;NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;   at ProjectFileTools.NuGetSearch.Feeds.Disk.NuGetV3DiskFeed.&lt;&gt;c__DisplayClass7_0.&lt;GetPackageNamesAsync&gt;b__0()&#x000D;&#x000A;   at System.Threading.Tasks.Task`1.InnerInvoke()&#x000D;&#x000A;   at System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at ProjectFileTools.NuGetSearch.Search.PackageSearchManager.TransformToPackageInfo(Task`1 arg)&#x000D;&#x000A;   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()&#x000D;&#x000A;   at System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#x000D;&#x000A;   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)&#x000D;&#x000A;   at System.Threading.Tasks.Task`1.get_Result()&#x000D;&#x000A;   at ProjectFileTools.NuGetSearch.Search.PackageFeedSearchJob`1.HandleCompletion(Task`1 task)&#x000D;&#x000A;   at ProjectFileTools.NuGetSearch.Search.PackageFeedSearchJob`1..ctor(IReadOnlyList`1 searchTasks, CancellationTokenSource cancellationTokenSource)&#x000D;&#x000A;   at ProjectFileTools.NuGetSearch.Search.PackageSearchManager.SearchPackageNamesInternal(String prefix, String tfm, IPackageQueryConfiguration config)&#x000D;&#x000A;   at ProjectFileTools.NuGetSearch.Search.PackageSearchManager.&lt;&gt;c__DisplayClass7_0.&lt;SearchPackageNames&gt;b__1(PackageNameQuery x)&#x000D;&#x000A;   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)&#x000D;&#x000A;   at ProjectFileTools.NuGetSearch.Search.PackageSearchManager.SearchPackageNames(String prefix, String tfm)&#x000D;&#x000A;   at ProjectFileTools.Completion.PackageCompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()&#x000D;&#x000A;   at ProjectFileTools.Completion.CompletionController.StartSession()&#x000D;&#x000A;   at ProjectFileTools.Completion.CompletionController.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchTextInputEvents&gt;b__6_0(KeyProcessor p, TextCompositionEventArgs args)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)&#x000D;&#x000A;---&gt; (Inner Exception #0) System.AggregateException: One or more errors occurred. ---&gt; System.IO.FileNotFoundException: Could not load file or assembly &apos;NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;   at ProjectFileTools.NuGetSearch.Feeds.Disk.NuGetV3DiskFeed.&lt;&gt;c__DisplayClass7_0.&lt;GetPackageNamesAsync&gt;b__0()&#x000D;&#x000A;   at System.Threading.Tasks.Task`1.InnerInvoke()&#x000D;&#x000A;   at System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at ProjectFileTools.NuGetSearch.Search.PackageSearchManager.TransformToPackageInfo(Task`1 arg)&#x000D;&#x000A;   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()&#x000D;&#x000A;   at System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;---&gt; (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly &apos;NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;NuGet.Frameworks, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos;&#x000D;&#x000A;   at ProjectFileTools.NuGetSearch.Feeds.Disk.NuGetV3DiskFeed.&lt;&gt;c__DisplayClass7_0.&lt;GetPackageNamesAsync&gt;b__0()&#x000D;&#x000A;   at System.Threading.Tasks.Task`1.InnerInvoke()&#x000D;&#x000A;   at System.Threading.Tasks.Task.Execute()&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;&lt;---&#x000D;&#x000A;&lt;---&#x000D;&#x000A;</description>

### Expected behavior
Intellisense should be shown

**Comment by adrianvmsft** [comment]
This is because NuGet/Home#5242 - the version of NuGet.Frameworks was updated to 15.3, however there are no binding redirects from the old version to the new version.

Workaround:
Edit devent.exe.config and insert the following snippet next to the other binding redirects
```xml
<dependentAssembly>
          <assemblyIdentity name="NuGet.Frameworks" publicKeyToken="31bf3856ad364e35" culture="neutral" />
          <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.3.0.0" />
        </dependentAssembly>
```

**Comment by adrianvmsft** [comment]
This issue doesn't repro anymore on recent builds of VS 15.3

**Comment by mlorbetske** [comment]
Yep, this should be fixed now

**Comment by SomeAnon42** [comment]
15.4.1
![image](https://user-images.githubusercontent.com/6377116/31789406-b406b568-b51a-11e7-9e01-b39bb72d7007.png)

```System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=4.3.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. at ProjectFileTools.NuGetSearch.Feeds.Disk.NuGetV3DiskFeed.<>c__DisplayClass7_0.<GetPackageNamesAsync>b__0() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of inner exception stack trace --- at ProjectFileTools.NuGetSearch.Search.PackageSearchManager.TransformToPackageInfo(Task`1 arg) at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at ProjectFileTools.NuGetSearch.Search.PackageFeedSearchJob`1.HandleCompletion(Task`1 task) at ProjectFileTools.NuGetSearch.Search.PackageFeedSearchJob`1..ctor(IReadOnlyList`1 searchTasks, CancellationTokenSource cancellationTokenSource) at ProjectFileTools.NuGetSearch.Search.PackageSearchManager.SearchPackageNamesInternal(String prefix, String tfm, IPackageQueryConfiguration config) at ProjectFileTools.NuGetSearch.Search.PackageSearchManager.<>c__DisplayClass7_0.<SearchPackageNames>b__1(PackageNameQuery x) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory) at ProjectFileTools.NuGetSearch.Search.PackageSearchManager.SearchPackageNames(String prefix, String tfm) at ProjectFileTools.Completion.PackageCompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets) at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start() at ProjectFileTools.Completion.CompletionController.StartSession() at ProjectFileTools.Completion.CompletionController.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at ProjectFileTools.GotoDefinitionController.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=4.3.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. at ProjectFileTools.NuGetSearch.Feeds.Disk.NuGetV3DiskFeed.<>c__DisplayClass7_0.<GetPackageNamesAsync>b__0() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of inner exception stack trace --- at ProjectFileTools.NuGetSearch.Search.PackageSearchManager.TransformToPackageInfo(Task`1 arg) at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) ---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=4.3.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'NuGet.Frameworks, Version=4.3.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35' at ProjectFileTools.NuGetSearch.Feeds.Disk.NuGetV3DiskFeed.<>c__DisplayClass7_0.<GetPackageNamesAsync>b__0() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]. <--- <--- ```

**Comment by SomeAnon42** [comment]
Binding redirects for newer builds
15.4.1
```
<dependentAssembly>
  <assemblyIdentity name="NuGet.Frameworks" publicKeyToken="31bf3856ad364e35" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.3.0.5" newVersion="4.4.0.3" />
</dependentAssembly>
```

15.5 Preview 1
```
<dependentAssembly>
  <assemblyIdentity name="NuGet.Frameworks" publicKeyToken="31bf3856ad364e35" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.3.0.5" newVersion="4.5.0.1" />
</dependentAssembly>
```

Hope this helps anybody.
