### ISSUE TITLE
Need Support for Nuget v2

### ISSUE THREAD

**Issue by passuied** [dotnet/ProjFileTools#59]
### Installed product versions
- Visual Studio: VS Enterprise 2017 15.8.9
- This extension: 1.3.1

### Description
NuGet Package intellisense works for packages hosted in nuget.org but not for packages hosted in our internal server.

### Steps to recreate
1. Edit csproj file in VS 2017
2. Hover over nuget.org package ==> Get Package+ version info and intellisense
2. Hover over 'internal' package ==> Intellisense doesn't work and hovering only provides title info

### Current behavior
Intellisense is not working for NuGet packages hosted in our Internal Package server

### Expected behavior
Intellisense works for NuGet packages hosted in our Internal Package server

**Comment by mlorbetske** [comment]
Sorry for the delay. There isn't a particular reason for not supporting v2, no. It's something that would be good to have, but due to other priorities not something I'll likely get to soon. Contributions to add this would definitely be welcome.

**Comment by passuied** [comment]
Hi, 
I might be able to work on this as I really enjoy this extension but it currently only work on nuget.org packages and not our internal server ones...

Will see how I can carve time and submit a PR

**Comment by passuied** [comment]
@mlorbetske  I have now implement NuGet v2. Please review attached PR.
Sorry for the delay ;)
Patrick
