### ISSUE TITLE
Not working with ReSharper enabled

### ISSUE THREAD

**Issue by trydis** [dotnet/ProjFileTools#7]
### Installed product versions
- Visual Studio: Enterprise 2017 RTW+26228.4
- This extension: 1.0.2

### Description
Intellisense doesn't work in csproj-files with ReSharper 2016.3.2 enabled. Works fine when it's disabled/suspended.

### Steps to recreate
1. Install/enable ReSharper 2016.3.2
2. Create a new console application
3. Right-click project in solution explorer and select "Edit projectname.csproj"
4. Write `<` inside an `ItemGroup`

### Current behavior
The only suggestion is to insert a comment.

### Expected behavior
It should list all possible suggestions, including `PackageReference`.

**Comment by mlorbetske** [comment]
@madskristensen do you know who would be good to reach out to for this?

**Comment by madskristensen** [comment]
I do not

**Comment by trydis** [comment]
Same behavior in 2017.1 EAP 6

**Comment by powelerl** [comment]
I have created a issue with Jetbrains.

https://youtrack.jetbrains.com/issue/RSRP-465979

**Comment by mlorbetske** [comment]
Closing this in preference to tracking on the Resharper side
